name: prive-admin

services:
  postgres:
    image: postgres
    container_name: prive-admin-postgres
    environment:
      POSTGRES_DB: prive-admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - prive-admin_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  prive-admin_postgres_data:
